import { NextRequest, NextResponse } from "next/server";
import { createZaiClient } from "@/lib/zai-client";

// AI report generation endpoint.
// Receives raw pasted course text and returns a structured report object
// generated by GLM (via z.ai), ready for preview & editing.

interface ParsedReport {
  namaKursus: string;
  tarikh: string;
  masa: string;
  lokasi: string;
  kehadiran: string;
  hadiran: number;
  jumlah: number;
  ringkasanAi: string;
  kelebihanAi: string;
  kelemahanAi: string;
  cadanganAi: string;
  pautanGform: string;
}

const SYSTEM_PROMPT = `Anda adalah penulis laporan latihan profesional untuk Al Amin Edu Oasis Sdn Bhd, sebuah organisasi latihan guru dan staf di Malaysia.

Tugas anda: terima TEKS MENTAH kursus yang ditampal oleh pengguna (format bebas, mungkin berbahasa Melayu/Inggeris, dengan maklumat seperti nama kursus, tarikh, masa, lokasi, kehadiran, kelebihan, kelemahan, pautan Google Form), kemudian jana kandungan laporan yang kemas, profesional dan berstruktur.

Output WAJIB dalam format JSON sahaja (tiada markdown, tiada penjelasan tambahan) dengan medan berikut:
{
  "namaKursus": "Nama kursus yang dikenal pasti (ringkas, profesional)",
  "tarikh": "Tarikh kursus dalam format yang jelas contoh '8 September 2026'",
  "masa": "Masa mula & tamat kursus contoh '08:30 pagi - 05:00 petang'",
  "lokasi": "Lokasi kursus dijalankan",
  "kehadiran": "Format pecahan contoh '16/16' jika diberi, jika tidak 'N/A'",
  "hadiran": <nombor peserta hadir, 0 jika tidak dinyatakan>,
  "jumlah": <nombor jumlah peserta dijangka, 0 jika tidak dinyatakan>,
  "ringkasanAi": "Satu perenggan ringkasan eksekutif (2-4 ayat) tentang kursus — objektif, pelaksanaan dan hasil secara profesional dalam Bahasa Melayu.",
  "kelebihanAi": "Rumusan kelebihan kursus. Gunakan format markdown bullet (setiap titik bermula dengan '- '). 3-6 perkara. Tulis dalam perenggan profesional Bahasa Melayu.",
  "kelemahanAi": "Rumusan kelemahan / isu / cabaran kursus. Gunakan format markdown bullet (setiap titik bermula dengan '- '). 2-5 perkataan isu. Bahasa Melayu profesional.",
  "cadanganAi": "Cadangan penambahbaikan untuk kursus akan datang. Gunakan format markdown bullet. 3-5 cadangan. Bahasa Melayu profesional.",
  "pautanGform": "Pautan Google Form maklum balas jika dinyatakan dalam input, jika tidak string kosong"
}

Panduan penulisan:
- Gunakan Bahasa Melayu formal & profesional.
- Jika maklumat tertentu tiada dalam input, gunakan nilai yang munasabah atau "N/A" (untuk teks) / 0 (untuk nombor).
- Untuk kelebihan & kelemahan, rumus dan kembangkan dari input mentah — jangan sekadar salin. Buat ayat yang kemas dan profesional.
- Pastikan JSON yang dikembalikan adalah sah (valid JSON) tanpa ulasan tambahan.`;

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { rawInput, penyedia } = body as { rawInput?: string; penyedia?: string };

    if (!rawInput || rawInput.trim().length < 10) {
      return NextResponse.json(
        { error: "Sila tampal maklumat kursus (minimum 10 aksara) sebelum menjana laporan." },
        { status: 400 }
      );
    }

    // Create ZAI client (works via config file in sandbox, or env vars in production)
    let zai;
    let lastError: Error | null = null;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        zai = await createZaiClient();
        break;
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        console.error(`[AI GENERATE] createZaiClient() attempt ${attempt} failed:`, lastError.message);
        if (attempt < 3) await new Promise((r) => setTimeout(r, 1000 * attempt));
      }
    }
    if (!zai) {
      return NextResponse.json(
        {
          error:
            "Konfigurasi AI tidak dijumpai. Setkan ZAI_BASE_URL, ZAI_API_KEY, ZAI_CHAT_ID, ZAI_USER_ID & ZAI_TOKEN dalam environment variables platform deployment anda.",
        },
        { status: 503 }
      );
    }

    let completion: any;
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        completion = await zai.chat.completions.create({
          messages: [
            { role: "system", content: SYSTEM_PROMPT },
            {
              role: "user",
              content: `Berikut ialah maklumat mentah kursus yang perlu dijana menjadi laporan:\n\n"""\n${rawInput.trim()}\n"""\n\nPenyedia (jika ada): ${penyedia || "Tidak dinyatakan"}\n\nSila jana laporan dalam format JSON seperti yang ditetapkan.`,
            },
          ],
          thinking: { type: "disabled" },
        });
        break;
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        console.error(`[AI GENERATE] completion attempt ${attempt} failed:`, lastError.message);
        if (attempt < 2) {
          await new Promise((r) => setTimeout(r, 1500));
          // Re-create ZAI client on retry (in case of stale config)
          try { zai = await createZaiClient(); } catch {}
        }
      }
    }
    if (!completion) {
      return NextResponse.json(
        { error: `AI gagal menjana respons selepas beberapa percubaan: ${lastError?.message || "ralat tidak diketahui"}` },
        { status: 502 }
      );
    }

    const content = completion.choices[0]?.message?.content ?? "";

    // Extract JSON from the response (robust against minor surrounding text)
    let parsed: ParsedReport;
    try {
      parsed = JSON.parse(content);
    } catch {
      const match = content.match(/\{[\s\S]*\}/);
      if (!match) {
        return NextResponse.json(
          { error: "AI tidak menjana respons JSON yang sah. Sila cuba sekali lagi." },
          { status: 502 }
        );
      }
      parsed = JSON.parse(match[0]);
    }

    const report: ParsedReport = {
      namaKursus: String(parsed.namaKursus || "Kursus Latihan").slice(0, 200),
      tarikh: String(parsed.tarikh || "N/A"),
      masa: String(parsed.masa || "N/A"),
      lokasi: String(parsed.lokasi || "N/A"),
      kehadiran: String(parsed.kehadiran || "N/A"),
      hadiran: Number(parsed.hadiran) || 0,
      jumlah: Number(parsed.jumlah) || 0,
      ringkasanAi: String(parsed.ringkasanAi || ""),
      kelebihanAi: String(parsed.kelebihanAi || ""),
      kelemahanAi: String(parsed.kelemahanAi || ""),
      cadanganAi: String(parsed.cadanganAi || ""),
      pautanGform: String(parsed.pautanGform || ""),
    };

    return NextResponse.json({ success: true, report });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Ralat tidak diketahui";
    console.error("[AI GENERATE ERROR]", message);
    return NextResponse.json(
      { error: `Gagal menjana laporan dengan AI: ${message}` },
      { status: 500 }
    );
  }
}
