import { NextRequest, NextResponse } from "next/server";
import { createZaiClient } from "@/lib/zai-client";

// AI report generation endpoint.
// Receives raw pasted course text and returns a structured report object
// generated by GLM (via z.ai), ready for preview & editing.

interface ParsedReport {
  namaKursus: string;
  tarikh: string;
  masa: string;
  lokasi: string;
  kehadiran: string;
  hadiran: number;
  jumlah: number;
  ringkasanAi: string;
  kelebihanAi: string;
  kelemahanAi: string;
  cadanganAi: string;
  pautanGform: string;
}

const SYSTEM_PROMPT = `Anda adalah penulis laporan latihan profesional untuk Al Amin Edu Oasis Sdn Bhd, sebuah organisasi latihan guru dan staf di Malaysia.

Tugas anda: terima TEKS MENTAH kursus yang ditampal oleh pengguna (format bebas, mungkin berbahasa Melayu/Inggeris), ekstrak maklumat penting, dan jana laporan berstruktur yang kemas dan profesional.

## Peraturan Ekstraksi Maklumat (SANGAT PENTING)

Anda MESTI cari dan letakkan maklumat di medan yang BETUL. Pengguna mungkin guna label berbeza:

- **namaKursus**: Cari nama kursus. Label mungkin: "Nama Kursus", "Tajuk", "Kursus", "Bengkel", "Modul", "Program". Ambil nilai selepas tanda titik bertindih (:). Buang label, kekalkan nama kursus sahaja.
- **tarikh**: Cari tarikh. Label mungkin: "Tarikh", "Hari", "Tanggal", "Date". Tukar ke format "D Bulan Tahun" (contoh: "15 September 2026"). Jika input "Isnin 15 Sept 2026", output "15 September 2026".
- **masa**: Cari masa. Label mungkin: "Masa", "Waktu", "Time", "Jam". Tukar ke format 12-jam yang jelas (contoh: "08:30 pagi - 05:00 petang"). Jika input "8 pagi hingga 5 petang", output "08:00 pagi - 05:00 petang".
- **lokasi**: Cari lokasi. Label mungkin: "Lokasi", "Tempat", "Venue", "Lokasi". Buang label, kekalkan lokasi sahaja.
- **kehadiran**: Cari bilangan kehadiran. Label mungkin: "Kehadiran", "Peserta", "Hadir", "Bilangan". Jika "18 daripada 20" atau "18/20", output "18/20".
- **hadiran**: Nombor peserta HADIR (contoh: 18 dari "18/20"). Jika hanya satu nombor diberi, anggap ia hadir dan jumlah sama.
- **jumlah**: Nombor JUMLAH peserta dijangka (contoh: 20 dari "18/20"). Jika hanya satu nombor, gunakan nombor yang sama.
- **pautanGform**: Cari URL yang mengandungi "forms.gle" atau "docs.google.com/forms". Jika tiada, string kosong.

## Output JSON (WAJIB, tiada markdown, tiada penjelasan)

{
  "namaKursus": "contoh: Bengkel Pedagogi Abad 21",
  "tarikh": "contoh: 15 September 2026",
  "masa": "contoh: 08:30 pagi - 05:00 petang",
  "lokasi": "contoh: Dewan Utama, Al Amin Edu Oasis",
  "kehadiran": "contoh: 18/20",
  "hadiran": 18,
  "jumlah": 20,
  "ringkasanAi": "Satu perenggan (2-4 ayat) ringkasan eksekutif: objektif kursus, pelaksanaan, dan hasil. Bahasa Melayu formal.",
  "kelebihanAi": "3-6 bullet (setiap satu bermula dengan '- '). Kembangkan dari input mentah menjadi ayat profesional. Contoh:\\n- Kandungan kursus relevan dengan keperluan semasa\\n- Penceramah berpengalaman dan interaktif",
  "kelemahanAi": "2-5 bullet (setiap satu bermula dengan '- '). Isu/cabaran kursus dalam ayat profesional.",
  "cadanganAi": "3-5 bullet (setiap satu bermula dengan '- '). Cadangan penambahbaikan untuk kursus akan datang.",
  "pautanGform": "URL Google Form jika ada, jika tidak string kosong"
}

## Panduan Penulisan
- Bahasa Melayu formal & profesional sahaja.
- Jika maklumat tertentu tiada, gunakan "N/A" (teks) atau 0 (nombor).
- Jangan sekadar salin input — rumus dan kembangkan menjadi ayat profesional.
- Pastikan JSON sah tanpa ulasan tambahan.

## Contoh
Input: "Tajuk: Kursus AI\\nHari: Isnin 15 Sept 2026\\nMasa 8pg-5ptg\\nTempat: Bilik Latihan\\nHadir: 16/16\\nKebaikan: bagus, menarik\\nKekurangan: masa pendek"
Output: {"namaKursus":"Kursus AI","tarikh":"15 September 2026","masa":"08:00 pagi - 05:00 petang","lokasi":"Bilik Latihan","kehadiran":"16/16","hadiran":16,"jumlah":16,"ringkasanAi":"...","kelebihanAi":"...","kelemahanAi":"...","cadanganAi":"...","pautanGform":""}`;

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { rawInput, penyedia } = body as { rawInput?: string; penyedia?: string };

    if (!rawInput || rawInput.trim().length < 10) {
      return NextResponse.json(
        { error: "Sila tampal maklumat kursus (minimum 10 aksara) sebelum menjana laporan." },
        { status: 400 }
      );
    }

    // Create ZAI client (works via config file in sandbox, or env vars in production)
    let zai;
    let lastError: Error | null = null;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        zai = await createZaiClient();
        break;
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        console.error(`[AI GENERATE] createZaiClient() attempt ${attempt} failed:`, lastError.message);
        if (attempt < 3) await new Promise((r) => setTimeout(r, 1000 * attempt));
      }
    }
    if (!zai) {
      return NextResponse.json(
        {
          error:
            "Konfigurasi AI tidak dijumpai. Setkan ZAI_BASE_URL, ZAI_API_KEY, ZAI_CHAT_ID, ZAI_USER_ID & ZAI_TOKEN dalam environment variables platform deployment anda.",
        },
        { status: 503 }
      );
    }

    let completion: any;
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        completion = await zai.chat.completions.create({
          messages: [
            { role: "system", content: SYSTEM_PROMPT },
            {
              role: "user",
              content: `Berikut ialah maklumat mentah kursus yang perlu dijana menjadi laporan:\n\n"""\n${rawInput.trim()}\n"""\n\nPenyedia (jika ada): ${penyedia || "Tidak dinyatakan"}\n\nSila jana laporan dalam format JSON seperti yang ditetapkan.`,
            },
          ],
          thinking: { type: "disabled" },
        });
        break;
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        console.error(`[AI GENERATE] completion attempt ${attempt} failed:`, lastError.message);
        if (attempt < 2) {
          await new Promise((r) => setTimeout(r, 1500));
          // Re-create ZAI client on retry (in case of stale config)
          try { zai = await createZaiClient(); } catch {}
        }
      }
    }
    if (!completion) {
      return NextResponse.json(
        { error: `AI gagal menjana respons selepas beberapa percubaan: ${lastError?.message || "ralat tidak diketahui"}` },
        { status: 502 }
      );
    }

    const content = completion.choices[0]?.message?.content ?? "";

    // Extract JSON from the response (robust against minor surrounding text)
    let parsed: ParsedReport;
    try {
      parsed = JSON.parse(content);
    } catch {
      const match = content.match(/\{[\s\S]*\}/);
      if (!match) {
        return NextResponse.json(
          { error: "AI tidak menjana respons JSON yang sah. Sila cuba sekali lagi." },
          { status: 502 }
        );
      }
      parsed = JSON.parse(match[0]);
    }

    const report: ParsedReport = {
      namaKursus: String(parsed.namaKursus || "Kursus Latihan").slice(0, 200),
      tarikh: String(parsed.tarikh || "N/A"),
      masa: String(parsed.masa || "N/A"),
      lokasi: String(parsed.lokasi || "N/A"),
      kehadiran: String(parsed.kehadiran || "N/A"),
      hadiran: Number(parsed.hadiran) || 0,
      jumlah: Number(parsed.jumlah) || 0,
      ringkasanAi: String(parsed.ringkasanAi || ""),
      kelebihanAi: String(parsed.kelebihanAi || ""),
      kelemahanAi: String(parsed.kelemahanAi || ""),
      cadanganAi: String(parsed.cadanganAi || ""),
      pautanGform: String(parsed.pautanGform || ""),
    };

    return NextResponse.json({ success: true, report });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Ralat tidak diketahui";
    console.error("[AI GENERATE ERROR]", message);
    return NextResponse.json(
      { error: `Gagal menjana laporan dengan AI: ${message}` },
      { status: 500 }
    );
  }
}
